Repository Port-In-The-Storm/Port-In-The-Storm, pull requests merged in 2023-12, with the labels that each got.

#39 Amend fixes
  Port House Rules/amend_qualities.xml
Labels: Optimization

#40 Removing Plague Cloud
  Port House Rules/amend_powers.xml
Labels: Pending Review

#43 Update manifest.xml
  Port House Rules/manifest.xml
Labels: Tek's Bullshit

#42 Port STT.xml fix
  Port Point Buy.xml
  Port Priority.xml
  Port STT.xml
Labels: bug

#44 Removed banned ware grades
  Port House Rules/amend_bioware.xml
  Port House Rules/amend_cyberware.xml
Labels: bug
